version: '3'
services:
  dropbox-new:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 17500:17500
    volumes:
      - ./Dropbox:/dropbox/Dropbox
      - /tmp:/tmp
      - ./db-conf:/dropbox/.dropbox
      
